#!/usr/bin/env bash
set -euo pipefail
source "$(cd "$(dirname "$0")" && pwd)/common.sh"

TASK_INPUT="${1:-}"
REPO_ENV_FILE="${2:-}"
[ -n "$TASK_INPUT" ] || fail "Uso: run-pipeline.sh 'Processar issue #42 ...' repos/seu.repo.env"
[ -f "$REPO_ENV_FILE" ] || fail "Arquivo de repo não encontrado: $REPO_ENV_FILE"

# shellcheck disable=SC1090
source "$REPO_ENV_FILE"

OPENCODE_BIN="${OPENCODE_BIN:-opencode}"
command -v "$OPENCODE_BIN" >/dev/null 2>&1 || fail "OpenCode não encontrado em OPENCODE_BIN=$OPENCODE_BIN"
command -v git >/dev/null 2>&1 || fail "git não encontrado"
command -v gh >/dev/null 2>&1 || fail "gh não encontrado"
[ -d "$LOCAL_PATH" ] || fail "LOCAL_PATH inválido: $LOCAL_PATH"

mkdir -p "$ROOT_DIR/state/logs" "$ROOT_DIR/state/runs"
RUN_ID="$(date +%Y%m%d-%H%M%S)-${REPO_NAME:-repo}"
LOG_FILE="$ROOT_DIR/state/logs/$RUN_ID.log"

slugify() {
  printf '%s' "$1" \
    | tr '[:upper:]' '[:lower:]' \
    | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//; s/-{2,}/-/g' \
    | cut -c1-48
}

run_cmd() {
  local label="$1"
  local cmd="$2"
  [ -n "$cmd" ] || return 0
  log "$label: $cmd"
  bash -lc "$cmd"
}

issue_number="$(printf '%s' "$TASK_INPUT" | grep -oE '#[0-9]+' | head -n1 | tr -d '#')"
kind="issue"
printf '%s' "$TASK_INPUT" | grep -qi 'pr #' && kind="pr"
raw_title="$(printf '%s' "$TASK_INPUT" | sed -E 's/^.*:[[:space:]]*//')"
[ -n "$raw_title" ] || raw_title="$TASK_INPUT"
branch_slug="$(slugify "$raw_title")"
[ -n "$branch_slug" ] || branch_slug="task"
branch_name="${AI_BRANCH_PREFIX:-ai}/${kind}-${issue_number:-manual}-${branch_slug}"
commit_prefix="${GIT_COMMIT_PREFIX:-feat}"
pr_title="${commit_prefix}: ${raw_title}"

if [ -n "$issue_number" ]; then
  pr_body="Closes #${issue_number}"
else
  pr_body="Automated change generated by OpenCode Agent Factory."
fi

orchestrator_rules=""
[ -f "$ROOT_DIR/agents/orchestrator.md" ] && orchestrator_rules="$(cat "$ROOT_DIR/agents/orchestrator.md")"
git_rules=""
[ -f "$ROOT_DIR/agents/git.md" ] && git_rules="$(cat "$ROOT_DIR/agents/git.md")"

PROMPT=$(cat <<EOF
Você está executando uma tarefa de engenharia no repositório local.

Tarefa:
$TASK_INPUT

Regras do orquestrador:
$orchestrator_rules

Regras Git:
$git_rules

Restrições obrigatórias:
- Trabalhe somente neste repositório local.
- Implemente o que for necessário para concluir a tarefa.
- Crie ou atualize testes obrigatoriamente.
- Rode e corrija até ficar verde em testes, lint e format.
- Não pergunte por autorização.
- Não faça git add, commit, push, PR ou merge; o shell fará isso automaticamente depois.
- Ao final, responda com DONE, BLOCKED ou NEEDS_HUMAN e um resumo curto.

Comandos do projeto:
- Test: ${TEST_COMMAND:-}
- Lint: ${LINT_COMMAND:-}
- Format: ${FORMAT_COMMAND:-}
- Build: ${BUILD_COMMAND:-}
EOF
)

cd "$LOCAL_PATH"

current_branch="$(git branch --show-current || true)"
if [ -n "$(git status --porcelain)" ]; then
  fail "Working tree não está limpo em $LOCAL_PATH. Commit/stash/revert antes de rodar a automação."
fi

if ! git config user.name >/dev/null 2>&1; then
  [ -n "${GIT_AUTHOR_NAME:-}" ] && git config user.name "$GIT_AUTHOR_NAME"
fi
if ! git config user.email >/dev/null 2>&1; then
  [ -n "${GIT_AUTHOR_EMAIL:-}" ] && git config user.email "$GIT_AUTHOR_EMAIL"
fi

git config user.name >/dev/null 2>&1 || fail "git user.name não configurado"
git config user.email >/dev/null 2>&1 || fail "git user.email não configurado"

git fetch origin "${BASE_BRANCH:-main}"
git checkout "${BASE_BRANCH:-main}"
git pull --ff-only origin "${BASE_BRANCH:-main}"
git checkout -B "$branch_name" "origin/${BASE_BRANCH:-main}"

set +e
(
  timeout "${MAX_RUNTIME_SECONDS:-600}" "$OPENCODE_BIN" run "$PROMPT"
) | tee "$LOG_FILE"
opencode_status=${PIPESTATUS[0]}
set -e

[ "$opencode_status" -eq 0 ] || fail "OpenCode retornou falha. Veja o log: $LOG_FILE"

run_cmd "Test" "${TEST_COMMAND:-}"
run_cmd "Lint" "${LINT_COMMAND:-}"
run_cmd "Format" "${FORMAT_COMMAND:-}"
run_cmd "Build" "${BUILD_COMMAND:-}"

if [ -n "${FORMAT_COMMAND:-}" ]; then
  run_cmd "Retest" "${TEST_COMMAND:-}"
  run_cmd "Relint" "${LINT_COMMAND:-}"
fi

if [ -z "$(git status --porcelain)" ]; then
  log "Nenhuma mudança detectada após a execução. Nada para commitar."
  [ -n "$current_branch" ] && git checkout "$current_branch" >/dev/null 2>&1 || true
  exit 0
fi

git add -A
git commit -m "$pr_title"
commit_sha="$(git rev-parse --short HEAD)"
pr_url=""
pr_number=""

if [ "${AUTO_PUSH:-false}" = "true" ]; then
  git push -u origin "$branch_name"
fi

if [ "${AUTO_PR:-false}" = "true" ] && [ "${AUTO_PUSH:-false}" = "true" ]; then
  existing_pr_url="$(gh pr list --repo "${REPO_OWNER}/${REPO_NAME}" --head "$branch_name" --json url --jq '.[0].url' 2>/dev/null || true)"
  if [ -n "$existing_pr_url" ] && [ "$existing_pr_url" != "null" ]; then
    pr_url="$existing_pr_url"
  else
    pr_url="$(gh pr create \
      --repo "${REPO_OWNER}/${REPO_NAME}" \
      --base "${BASE_BRANCH:-main}" \
      --head "$branch_name" \
      --title "$pr_title" \
      --body "$pr_body")"
  fi
  pr_number="$(gh pr view "$branch_name" --repo "${REPO_OWNER}/${REPO_NAME}" --json number --jq '.number')"
fi

if [ "${AUTO_COMMENT_ON_ISSUE:-false}" = "true" ] && [ -n "$issue_number" ]; then
  comment_body="Automação concluída em
- branch: \`$branch_name\`
- commit: \`$commit_sha\`"
  if [ -n "$pr_url" ]; then
    comment_body="${comment_body}
- PR: $pr_url"
  fi
  gh issue comment "$issue_number" --repo "${REPO_OWNER}/${REPO_NAME}" --body "$comment_body" >/dev/null
fi

if [ "${AUTO_MERGE_ONLY_GREEN:-false}" = "true" ] && [ -n "$pr_number" ]; then
  merge_method="${PR_MERGE_METHOD:-squash}"
  if ! gh pr merge "$pr_number" --repo "${REPO_OWNER}/${REPO_NAME}" --"$merge_method" --delete-branch; then
    gh pr merge "$pr_number" --repo "${REPO_OWNER}/${REPO_NAME}" --"$merge_method" --delete-branch --auto
  fi
fi

if [ -n "$current_branch" ]; then
  git checkout "$current_branch" >/dev/null 2>&1 || true
fi

log "Pipeline concluído. Branch=$branch_name Commit=$commit_sha${pr_url:+ PR=$pr_url}"